services:
  backend:
    build: ./backend
    container_name: back-nitin
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: front-nitin
    ports:
      - "100:100"
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    container_name: caddy-nitin
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

  volumes:
  caddy_data:
  caddy_config:
